apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prior-auth-service
  labels:
    app: prior-auth-service
spec:
  type: {{ .Values.priorAuthService.service.type }}
  ports:
    - port: {{ .Values.priorAuthService.service.port }}
      targetPort: 8083
      protocol: TCP
      name: http
  selector:
    app: prior-auth-service
