apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fhir-server
  labels:
    app: fhir-server
spec:
  type: {{ .Values.fhirServer.service.type }}
  ports:
    - port: {{ .Values.fhirServer.service.port }}
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: fhir-server
